modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/FirEmerald/CustomBGM/issues"
[[mods]]
modId="custombgm"
version="${file.jarVersion}"
displayName="CustomBGM"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/FirEmerald/CustomBGM"
logoFile="logo.png"
#credits=""
authors="FirEmerald"
description='''Library that allows modders, resource pack makers, and map makers to add and customize background music.
Also acts as a utility to enable arbitrary loop points for sounds.'''
[[dependencies.custombgm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
	