modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/FirEmerald/CustomBGM/issues"
[[mods]]
modId="custombgm"
version="${file.jarVersion}"
displayName="Custom BGM"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/custombgm"
logoFile="custombgm.png"
credits="FirEmerald"
authors="FirEmerald"
description='''
Framework for mods to add in sounds with custom loop points, as well setting music for biomes or biome tags
Also allows for changing of the title screen music via config
'''
[[dependencies.custombgm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.custombgm]]
    modId="fecore"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
